### ISSUE TITLE
Pycrypto error 

### ISSUE THREAD

**Issue by nehatkkhan786** [Cadmus/paywix#46]
* paywix version:
* Python version:
* Operating System:

When I try to install paywix with python 3.7 and pip it gives pycrypto error. when I install pycryptodome as pycrypto doesn't support python3 but still can't install paywix

**Comment by renjithsraj** [comment]
I never tries this package with 3.7 version, the updated package will release by this week, will update you.

**Comment by nehatkkhan786** [comment]
Great! Thanks a lot
